config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :contacts, path: '', path_names: {
    sign_in: 'sign_in', sign_out: 'sign_out'
  }

  devise_for :admins, path_names: {
    sign_in: 'sign_in', sign_out: 'sign_out'
  }, controllers: { sessions: 'admins/sessions' }

  root 'dashboard#index'

  namespace :admins do
    get 'dashboard', to: 'dashboard#index'
  end
  get 'dashboard', to: 'dashboard#index'
  
  resources :companies
  resources :agencies
  resources :employees
  resources :agents
  resources :csv_imports
end
  

app/views/layouts/shared/_admin_navbar.html.erb
<div class="grid grid-cols-1">
  <!-- Navbar -->
  <nav class="bg-gray-800 p-4" data-controller="menu">
    <div class="grid grid-cols-12">
      <div class="col-start-1">
        <a href="#" class="text-white text-2xl font-bold">Admin Panel</a>
      </div>
      <div class="col-start-3 col-end-5 col-span-2">
        <div class="hidden md:flex justify-start space-x-4">
          <%= link_to 'Companies', companies_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium", data: { turbo_stream: true, turbo_frame: 'tab-content' } %>
          <%= link_to 'Agencies', agencies_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium", data: { turbo_stream: true, turbo_frame: 'tab-content' } %>
        </div>
      </div>

      <div class="col-end-13">
        <%= link_to 'Sign Out', destroy_admin_session_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium", data: { turbo_method: :delete } %>
      </div>

      <div class="md:hidden">
        <button data-action="click->menu#toggle" class="text-white hover:bg-gray-700 p-2 rounded-md">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>

    <div class="md:hidden hidden" data-menu-target="menu">
      <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
        <%= link_to 'Companies', companies_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium", data: { turbo_stream: true, turbo_frame: 'tab-content' } %>
        <%= link_to 'Agencies', agencies_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium", data: { turbo_stream: true, turbo_frame: 'tab-content' } %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/shared/_empty_modal.html.erb
<%= turbo_frame_tag "modal", class: "hidden fixed inset-0 z-50 flex items-center justify-center", data: { controller: "modal" } do %>
  <div class="absolute inset-0 bg-gray-900 bg-opacity-50" data-action="click->modal#hide"></div>
  <div class="relative bg-white rounded-lg shadow-xl p-6 w-[500px] z-10" data-modal-target="content">
  </div>
<% end %>

app/views/layouts/shared/_navbar.html.erb
<div class="grid grid-cols-1">
  <nav class="bg-gray-800 p-4" data-controller="menu">
    <div class="grid grid-cols-12">
      <div class="col-end-13">
        <%= link_to 'Sign Out', destroy_contact_session_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium", data: { turbo_method: :delete } %>
      </div>
    </div>
  </nav>
</div>