config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :contacts, path: '', path_names: {
    sign_in: 'sign_in', sign_out: 'sign_out'
  }

  devise_for :admins, path_names: {
    sign_in: 'sign_in', sign_out: 'sign_out'
  }, controllers: { sessions: 'admins/sessions' }

  root 'dashboard#index'

  namespace :admins do
    get 'dashboard', to: 'dashboard#index'
  end
  get 'dashboard', to: 'dashboard#index'
  
  resources :companies
  resources :agencies
  resources :employees
  resources :agents
  resources :csv_imports
end
  

app/models/agency.rb
class Agency < ApplicationRecord
  has_many :agents, dependent: :destroy
  has_one :contact, as: :contactable, dependent: :destroy
  accepts_nested_attributes_for :contact, allow_destroy: true

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, presence: true, length: { minimum: 10, maximum: 15 }
  validates :address_line_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :zip, presence: true, format: { with: /\A[A-Za-z0-9]{5,10}\z/, message: "must be alphanumeric and between 5 to 10 characters long" }
  validates :website, allow_blank: true, format: { with: URI::DEFAULT_PARSER.make_regexp, message: "must be a valid URL" }

  def full_address
    [address_line_1, address_line_2, city, state, country, zip].compact.join(', ')
  end
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_agency, only: [:edit, :update, :show, :destroy]

  def new
    @agency = Agency.new
    @agency.build_contact
  
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("tab-content", partial: 'agencies/form', locals: { agency: @agency })
      end
    end
  end  

  def index
    @agencies = Agency.all
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("tab-content", partial: "agencies/index", locals: { agencies: @agencies })
      end
    end
  end
  
  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("tab-content", partial: "agencies/form", locals: { agency: @agency })
      end
    end
  end

  def show
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("tab-content", partial: "agencies/details", locals: { agency: @agency })
      end
    end
  end

  def create
    updated_params = agency_params
    temp_password = SecureRandom.hex(8)
    updated_params[:contact_attributes] = updated_params[:contact_attributes].merge(password: temp_password, password_confirmation: temp_password)
    @agency = Agency.new(updated_params)
    if @agency.save
      respond_to do |format|
        format.turbo_stream do
          redirect_to agencies_path
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("tab-content", partial: "agencies/form", locals: { agency: @agency })
        end
      end
    end
  end

  def update
    if @agency.update(agency_params)
      respond_to do |format|
        format.turbo_stream do
          redirect_to agencies_path
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("tab-content", partial: "agencies/form", locals: { agency: @agency })
        end
      end
    end
  end

  def destroy
    @agency.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("agency_#{@agency.id}")
      end
    end
  end

  private

  def set_agency
    @agency = Agency.find(params[:id])
  end

  def agency_params
    params.require(:agency).permit(:name, :email, :phone, :address_line_1, :address_line_2, :city, :state, :country, :zip, :website, contact_attributes: [:id, :first_name, :last_name, :email, :phone])
  end
end

app/views/agencies/_agency.html.erb
<tr id="agency_<%= agency.id %>" class="mb-4">
  <td class="text-center"><%= agency.name %></td>
  <td class="text-center"><%= agency.email %></td>
  <td class="text-center"><%= agency.phone %></td>
  <td class="flex justify-evenly">
    <%= link_to agency_path(agency), data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' do %>
      <%= heroicon "eye", variant: :solid, options: { class: "h-6 w-6 text-blue-500" } %>
    <% end %>
    <%= link_to edit_agency_path(agency), data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' do %>
      <%= heroicon "pencil", variant: :solid, options: { class: "h-6 w-6 text-blue-500" } %>
    <% end %>
    <%= link_to agency_path(agency), method: :delete, data: { turbo_method: :delete, turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' do %>
      <%= heroicon "trash", variant: :solid, options: { class: "h-6 w-6 text-blue-500" } %>
    <% end %>
  </td>
</tr>

app/views/agencies/_details.html.erb
<%= turbo_frame_tag 'tab-content' do %>
  <div class="p-4 shadow-xl">
    <div class="grid grid-cols-12 bg-gray-500 items-center">
      <h2 class="col-start-1 col-span-3 text-lg left font-bold mb-4 px-5 py-5 text-white"><%= "#{agency.name}(#{agency.email})"%>
        </br>
        website: <span class="underline"><%= link_to agency.website, agency.website %></span>
        </br>
        address: <span><%= agency.full_address %></span>
        </br>
        contact us: <span><%= agency.phone %></span>
      </h2>
      <%= link_to 'Back', agencies_path, data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'col-start-10 rounded mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' %>
      <%= link_to '+ New Agent', new_agent_path(agency_id: agency.id), data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'col-end-13 col-span-2 rounded mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' %>
    </div>
    <table class="table-fixed w-full text-sm mt-5">
      <thead>
        <tr>
          <th class="py-5">Name</th>
          <th class="py-5">Email</th>
          <th class="py-5">Phone</th>
          <th class="py-5">Agent ID</th>
          <th class="py-5">Actions</th>
        </tr>
      </thead>
      <tbody id="agents-list">
        <% agency.agents.each do |agent|%>
          <%= render 'agents/agent', agent: agent, agency: agency %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/agencies/_form.html.erb
<%= turbo_frame_tag 'tab-content' do %>
  <div class="p-4 shadow-xl">
    <div class="flex w-full bg-gray-500 justify-between items-center">
      <h2 class="text-lg text-center font-bold mb-4 px-5 py-5 text-white">AGENCIES</h2>
      <%= link_to 'Back', agencies_path, data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 rounded bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' %>
    </div>
    <div class="flex justify-center py-10"> 
    
    <%= form_with model: agency, url: agency.id.nil? ? agencies_path : agency_path(agency), class: "w-3/4", data: { turbo_frame: 'tab-content' } do |f| %>
        <div class="grid grid-cols-3 gap-4">
          <div>
            <div class="mb-4">
              <%= f.label :name, 'Name', class: 'block text-gray-700' %>
              <%= f.text_field :name, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:name].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:name].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :email, 'Email', class: 'block text-gray-700' %>
              <%= f.email_field :email, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:email].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:email].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :phone, 'Phone', class: 'block text-gray-700' %>
              <%= f.telephone_field :phone, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:phone].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:phone].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :website, 'Website', class: 'block text-gray-700' %>
              <%= f.url_field :website, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:website].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:website].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :address_line_1, 'Address Line 1', class: 'block text-gray-700' %>
              <%= f.text_field :address_line_1, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:address_line_1].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:address_line_1].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :address_line_2, 'Address Line 2', class: 'block text-gray-700' %>
              <%= f.text_field :address_line_2, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:address_line_2].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:address_line_2].first %></p>
              <% end %>
            </div>
          </div>

          <div>
            <div class="mb-4">
              <%= f.label :city, 'City', class: 'block text-gray-700' %>
              <%= f.text_field :city, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:city].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:city].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :state, 'State', class: 'block text-gray-700' %>
              <%= f.text_field :state, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:state].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:state].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :country, 'Country', class: 'block text-gray-700' %>
              <%= f.text_field :country, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:country].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:country].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :zip, 'ZIP Code', class: 'block text-gray-700' %>
              <%= f.text_field :zip, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if agency.errors[:zip].any? %>
                <p class="text-red-500 text-xs mt-1"><%= agency.errors[:zip].first %></p>
              <% end %>
            </div>
          </div>
          <div>
            <h2 class="font-bold text-center">Contact Information</h3>
            <%= f.fields_for :contact do |contact_form| %>
               <%= contact_form.hidden_field :id %>
              <div class="mb-4">
                <%= contact_form.label :first_name, 'First Name', class: 'block text-gray-700' %>
                <%= contact_form.text_field :first_name, class: 'block w-full border border-gray-300 p-2 rounded' %>
                <% if contact_form.object.errors[:first_name].any? %>
                  <p class="text-red-500 text-xs mt-1"><%= contact_form.object.errors[:first_name].first %></p>
                <% end %>
              </div>
        
              <div class="mb-4">
                <%= contact_form.label :last_name, 'Last Name', class: 'block text-gray-700' %>
                <%= contact_form.text_field :last_name, class: 'block w-full border border-gray-300 p-2 rounded' %>
                <% if contact_form.object.errors[:last_name].any? %>
                  <p class="text-red-500 text-xs mt-1"><%= contact_form.object.errors[:last_name].first %></p>
                <% end %>
              </div>
        
              <div class="mb-4">
                <%= contact_form.label :email, 'Email', class: 'block text-gray-700' %>
                <%= contact_form.email_field :email, class: 'block w-full border border-gray-300 p-2 rounded' %>
                <% if contact_form.object.errors[:email].any? %>
                  <p class="text-red-500 text-xs mt-1"><%= contact_form.object.errors[:email].first %></p>
                <% end %>
              </div>
        
              <div class="mb-4">
                <%= contact_form.label :phone, 'Phone', class: 'block text-gray-700' %>
                <%= contact_form.telephone_field :phone, class: 'block w-full border border-gray-300 p-2 rounded' %>
                <% if contact_form.object.errors[:phone].any? %>
                  <p class="text-red-500 text-xs mt-1"><%= contact_form.object.errors[:phone].first %></p>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="grid grid-cols-1">
          <div class="text-center">
            <%= link_to 'Cancel', agencies_path, data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'bg-red-700 text-white px-4 py-2 rounded' %>
            <%= f.submit 'Save', class: 'px-4 py-2 bg-blue-500 text-white rounded' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/agencies/_index.html.erb
<%= turbo_frame_tag 'tab-content' do %>
  <div class="p-4 shadow-xl">
    <div class="flex w-full bg-gray-500 justify-between items-center">
      <h2 class="text-lg text-center font-bold mb-4 px-5 py-5 text-white">AGENCIES</h2>
      <%= link_to '+ New Agency', new_agency_path, data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' %>
    </div>
    <table class="table-fixed w-full text-sm mt-5">
      <thead>
        <tr>
          <th class="py-5">Name</th>
          <th class="py-5">Email</th>
          <th class="py-5">Phone</th>
          <th class="py-5">Actions</th>
        </tr>
      </thead>
      <tbody id="agencies-list">
        <% agencies.each do |agency|%>
          <%= render 'agencies/agency', agency: agency %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/agencies/index.html.erb
<%= turbo_frame_tag 'tab-content' do %>
  <%= render partial: 'agencies/index', locals: { agencies: @agencies } %>
<% end %>