config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :contacts, path: '', path_names: {
    sign_in: 'sign_in', sign_out: 'sign_out'
  }

  devise_for :admins, path_names: {
    sign_in: 'sign_in', sign_out: 'sign_out'
  }, controllers: { sessions: 'admins/sessions' }

  root 'dashboard#index'

  namespace :admins do
    get 'dashboard', to: 'dashboard#index'
  end
  get 'dashboard', to: 'dashboard#index'
  
  resources :companies
  resources :agencies
  resources :employees
  resources :agents
  resources :csv_imports
end
  

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees, dependent: :destroy
  has_many :policies
  has_one :contact, as: :contactable, dependent: :destroy
  accepts_nested_attributes_for :contact, allow_destroy: true

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, presence: true, length: { minimum: 10, maximum: 15 }
  validates :address_line_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :zip, presence: true, format: { with: /\A[A-Za-z0-9]{5,10}\z/, message: "must be alphanumeric and between 5 to 10 characters long" }
  validates :website, allow_blank: true, format: { with: URI::DEFAULT_PARSER.make_regexp, message: "must be a valid URL" }

  def full_address
    [address_line_1, address_line_2, city, state, country, zip].compact.join(', ')
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_company, only: [:edit, :update, :show, :destroy]

  def new
    @company = Company.new
    @company.build_contact
  
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("tab-content", partial: 'companies/form', locals: { company: @company })
      end
    end
  end  

  def index
    @companies = Company.all
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("tab-content", partial: "companies/index", locals: { companies: @companies })
      end
    end
  end
  
  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("tab-content", partial: "companies/form", locals: { company: @company })
      end
    end
  end

  def show
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("tab-content", partial: "companies/details", locals: { company: @company })
      end
    end
  end

  def create
    updated_params = company_params
    temp_password = SecureRandom.hex(8)
    updated_params[:contact_attributes] = updated_params[:contact_attributes].merge(password: temp_password, password_confirmation: temp_password)
    @company = Company.new(updated_params)
    if @company.save
      respond_to do |format|
        format.turbo_stream do
          redirect_to companies_path
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("tab-content", partial: "companies/form", locals: { company: @company })
        end
      end
    end
  end

  def update
    if @company.update(company_params)
      respond_to do |format|
        format.turbo_stream do
          redirect_to companies_path
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("tab-content", partial: "companies/form", locals: { company: @company })
        end
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("company_#{@company.id}")
      end
    end
  end

  private
  
  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :email, :phone, :address_line_1, :address_line_2, :city, :state, :country, :zip, :website, :industry, contact_attributes: [:id, :first_name, :last_name, :email, :phone])
  end
end

app/views/companies/_company.html.erb
<tr id="company_<%= company.id %>" class="mb-4">
  <td class="text-center"><%= company.name %></td>
  <td class="text-center"><%= company.email %></td>
  <td class="text-center"><%= company.phone %></td>
  <td class="flex justify-evenly">
    <%= link_to company_path(company), data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' do %>
      <%= heroicon "eye", variant: :solid, options: { class: "h-6 w-6 text-blue-500" } %>
    <% end %>
    <%= link_to edit_company_path(company), data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' do %>
      <%= heroicon "pencil", variant: :solid, options: { class: "h-6 w-6 text-blue-500" } %>
    <% end %>
    <%= link_to company_path(company), method: :delete, data: { turbo_method: :delete, turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' do %>
      <%= heroicon "trash", variant: :solid, options: { class: "h-6 w-6 text-blue-500" } %>
    <% end %>
  </td>
</tr>

app/views/companies/_details.html.erb
<%= turbo_frame_tag 'tab-content' do %>
  <div class="p-4 shadow-xl">
    <%= turbo_stream_from "progress-container" %>

    <div id="progress-container">
      <%= render partial: "csv_imports/progress", locals: { progress: 0 } %>
      <%= render partial: "csv_imports/success_message", locals: { message: "" } %>
    </div>
    <div class="grid grid-cols-12 bg-gray-500 items-center">
      <h2 class="col-start-1 col-span-3 text-lg left font-bold mb-4 px-5 py-5 text-white"><%= "#{company.name}(#{company.email})"%>
        </br>
        website: <span class="underline"><%= link_to company.website, company.website %></span>
        </br>
        address: <span><%= company.full_address %></span>
        </br>
        contact us: <span><%= company.phone %></span>
      </h2>
      <%= link_to "Refresh", company_path(company), data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'col-end-8 mr-5 text-white h-[50px] px-3 py-3 font-bold'%>
      <%= link_to "Import CSV", new_csv_import_path(company_id: company.id), data: { turbo_stream: true, turbo_frame: "modal" }, class: "col-end-9 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold" %>
      <%= link_to '+ New Employee', new_employee_path(company_id: company.id), data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'col-start-10 col-span-2 rounded mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' %>
      <%= link_to 'Back', companies_path, data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'col-end-13 rounded mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' %>
    </div>
    <table class="table-fixed w-full text-sm mt-5">
      <thead>
        <tr>
          <th class="py-5">Name</th>
          <th class="py-5">Email</th>
          <th class="py-5">Phone</th>
          <th class="py-5">Employee ID</th>
          <th class="py-5">Actions</th>
        </tr>
      </thead>
      <tbody id="employees-list">
        <% company.employees.each do |employee|%>
          <%= render 'employees/employee', employee: employee, company: company %>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= render 'layouts/shared/empty_modal'%>
<% end %>

app/views/companies/_form.html.erb
<%= turbo_frame_tag 'tab-content' do %>
  <div class="p-4 shadow-xl">
    <div class="flex w-full bg-gray-500 justify-between items-center">
      <h2 class="text-lg text-center font-bold mb-4 px-5 py-5 text-white">COMPANIES</h2>
      <%= link_to 'Back', companies_path, data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 rounded bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' %>
    </div>
    <div class="flex justify-center py-10"> 
    
    <%= form_with model: company, url: company.id.nil? ? companies_path : company_path(company), class: "w-3/4", data: { turbo_frame: 'tab-content' } do |f| %>
        <div class="grid grid-cols-3 gap-4">
          <div>
            <div class="mb-4">
              <%= f.label :name, 'Name', class: 'block text-gray-700' %>
              <%= f.text_field :name, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:name].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:name].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :email, 'Email', class: 'block text-gray-700' %>
              <%= f.email_field :email, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:email].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:email].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :phone, 'Phone', class: 'block text-gray-700' %>
              <%= f.telephone_field :phone, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:phone].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:phone].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :website, 'Website', class: 'block text-gray-700' %>
              <%= f.url_field :website, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:website].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:website].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :address_line_1, 'Address Line 1', class: 'block text-gray-700' %>
              <%= f.text_field :address_line_1, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:address_line_1].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:address_line_1].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :address_line_2, 'Address Line 2', class: 'block text-gray-700' %>
              <%= f.text_field :address_line_2, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:address_line_2].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:address_line_2].first %></p>
              <% end %>
            </div>
          </div>

          <div>
            <div class="mb-4">
              <%= f.label :city, 'City', class: 'block text-gray-700' %>
              <%= f.text_field :city, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:city].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:city].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :state, 'State', class: 'block text-gray-700' %>
              <%= f.text_field :state, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:state].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:state].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :country, 'Country', class: 'block text-gray-700' %>
              <%= f.text_field :country, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:country].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:country].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :zip, 'ZIP Code', class: 'block text-gray-700' %>
              <%= f.text_field :zip, class: 'block w-full border border-gray-300 p-2 rounded' %>
              <% if company.errors[:zip].any? %>
                <p class="text-red-500 text-xs mt-1"><%= company.errors[:zip].first %></p>
              <% end %>
            </div>

            <div class="mb-4">
              <%= f.label :industry, 'Industry', class: 'block text-gray-700' %>
              <%= f.text_field :industry, class: 'block w-full border border-gray-300 p-2 rounded' %>
            </div>
          </div>
          <div>
            <h2 class="font-bold text-center">Contact Information</h3>
            <%= f.fields_for :contact do |contact_form| %>
               <%= contact_form.hidden_field :id %>
              <div class="mb-4">
                <%= contact_form.label :first_name, 'First Name', class: 'block text-gray-700' %>
                <%= contact_form.text_field :first_name, class: 'block w-full border border-gray-300 p-2 rounded' %>
                <% if contact_form.object.errors[:first_name].any? %>
                  <p class="text-red-500 text-xs mt-1"><%= contact_form.object.errors[:first_name].first %></p>
                <% end %>
              </div>
        
              <div class="mb-4">
                <%= contact_form.label :last_name, 'Last Name', class: 'block text-gray-700' %>
                <%= contact_form.text_field :last_name, class: 'block w-full border border-gray-300 p-2 rounded' %>
                <% if contact_form.object.errors[:last_name].any? %>
                  <p class="text-red-500 text-xs mt-1"><%= contact_form.object.errors[:last_name].first %></p>
                <% end %>
              </div>
        
              <div class="mb-4">
                <%= contact_form.label :email, 'Email', class: 'block text-gray-700' %>
                <%= contact_form.email_field :email, class: 'block w-full border border-gray-300 p-2 rounded' %>
                <% if contact_form.object.errors[:email].any? %>
                  <p class="text-red-500 text-xs mt-1"><%= contact_form.object.errors[:email].first %></p>
                <% end %>
              </div>
        
              <div class="mb-4">
                <%= contact_form.label :phone, 'Phone', class: 'block text-gray-700' %>
                <%= contact_form.telephone_field :phone, class: 'block w-full border border-gray-300 p-2 rounded' %>
                <% if contact_form.object.errors[:phone].any? %>
                  <p class="text-red-500 text-xs mt-1"><%= contact_form.object.errors[:phone].first %></p>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="grid grid-cols-1">
          <div class="text-center">
            <%= link_to 'Cancel', companies_path, data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'bg-red-700 text-white px-4 py-2 rounded' %>
            <%= f.submit 'Save', class: 'px-4 py-2 bg-blue-500 text-white rounded' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/companies/_index.html.erb
<%= turbo_frame_tag 'tab-content' do %>
  <div class="p-4 shadow-xl">
    <div class="flex w-full bg-gray-500 justify-between items-center mt-4">
      <h2 class="text-lg text-center font-bold mb-4 px-5 py-5 text-white">COMPANIES</h2>
      <%= link_to '+ New Company', new_company_path, data: { turbo_stream: true, turbo_frame: 'tab-content' }, class: 'mr-5 bg-white text-gray-500 h-[50px] px-3 py-3 font-bold' %>
    </div>
    <table class="table-fixed w-full text-sm mt-5">
      <thead>
        <tr>
          <th class="py-5">Name</th>
          <th class="py-5">Email</th>
          <th class="py-5">Phone</th>
          <th class="py-5">Actions</th>
        </tr>
      </thead>
      <tbody id="companies-list">
        <% companies.each do |company|%>
          <%= render 'companies/company', company: company %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>